name: Build Electron App Linux AppImage

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Package Electron App for Linux
      run: npm run package-linux
    - name: Upload AppImage
      uses: actions/upload-artifact@v3.1.2
      with:
        name: lpff.appimage
        path: dist/lpff-1.0.0.appimage
