name: Build Electron App Windows

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Package Electron App for Windows
      run: npm run package-win

    - name: Upload Setup
      uses: actions/upload-artifact@v3.1.2
      with:
        name: windows-setup.exe
        path: dist/lpff Setup 1.0.0.exe
