name: Build Electron App Windows

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js and NPM
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm install

    - name: Package Electron App for Windows
      if: runner.os == 'windows-latest'
      run: npm run package-win

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      with:
        tag: "v1"

    - name: Upload Windows EXEs
      uses: actions/upload-artifact@v2
      with:
        name: lpff-Windows-EXEs
        path: |
          dist/lpff-1.0.0 Setup.exe
          dist/lpff-1.0.0.exe
